Repository WhileNotSuccess/project_OIC-Frontend_NextJS-deployment-repo, pull requests merged in 2025-05, with the labels that each got.

#52 🐛 fix : Update the fetch URL according to the API changes
  web/src/app/(NoLayout)/components/RegisterCompo.tsx
  web/src/app/(TitleLayout)/admin/components/CheckAdmin.tsx
  web/src/app/(TitleLayout)/components/Editor.tsx
  web/src/app/(TitleLayout)/components/EditorButton.tsx
  web/src/app/(TitleLayout)/components/HtmlDocsHeaderProps.tsx
  web/src/app/(TitleLayout)/components/NameChangeModal.tsx
Labels: 🐛 BugFix

#63 어드민 페이지 제작 및 자잘한 오류수정
  docker-compose.yml
  web/src/app/(TitleLayout)/admin/components/AdminComponent.tsx
  web/src/app/(TitleLayout)/admin/components/BoardPageContentForModal.tsx
  web/src/app/(TitleLayout)/admin/components/Countries.tsx
  web/src/app/(TitleLayout)/admin/components/DeleteModal.tsx
  web/src/app/(TitleLayout)/admin/components/GlobalPrograms.tsx
  web/src/app/(TitleLayout)/admin/components/GlobalProgramsModal.tsx
  web/src/app/(TitleLayout)/admin/components/GlobalProgramsPostSelectModal.tsx
  web/src/app/(TitleLayout)/admin/components/PrideModal.tsx
  web/src/app/(TitleLayout)/admin/components/PrideOfYJU.tsx
  web/src/app/(TitleLayout)/admin/components/StaffComponent.tsx
  web/src/app/(TitleLayout)/admin/components/StaffModal.tsx
  web/src/app/(TitleLayout)/admin/layout.tsx
  web/src/app/(TitleLayout)/admin/page.tsx
  web/src/app/(TitleLayout)/components/Editor.tsx
  web/src/app/(TitleLayout)/components/EditorButton.tsx
  web/src/app/(TitleLayout)/components/EditorTinyMCE.tsx
  web/src/app/(TitleLayout)/components/HtmlDocsHeaderProps.tsx
  web/src/app/(TitleLayout)/components/LoginCompo.tsx
  web/src/app/(TitleLayout)/staff/components/StaffMapCompo.tsx
  web/src/app/common/types.tsx
Labels: ⭐ Feature, 🐛 BugFix

#69 🐛 fix : 메인 PrideOfYJU 높이 수정, 글로벌 프로그램 링크 수정
  web/src/app/(NoTitleLayout)/home/components/HomeCompo.tsx
  web/src/app/(TitleLayout)/global/[category]/components/GlobalCarousel.tsx
Labels: 🐛 BugFix

#71 env update
  .github/workflows/deploy.yml
  web/Dockerfile
Labels: ⭐ Feature
