Repository WhileNotSuccess/project_OIC-Frontend_NextJS-deployment-repo, pull requests merged in 2025-04, with the labels that each got.

#14 ✏️ chore : change react version 19 -> 18
  docker-compose.yml
  web/package-lock.json
  web/package.json
Labels: enhancement

#18 ✏️ chore : update github template
  .github/ISSUE_TEMPLATE/bug_template.md
  .github/ISSUE_TEMPLATE/etc.template.md
  .github/ISSUE_TEMPLATE/feature_temlplate.md
  .github/ISSUE_TEMPLATE/refactoring_template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⭐ Feature

#22 SideMenu 제작, Title.tsx 사진 수정
  web/public/images/japan.png
  web/public/images/korean.png
  web/public/images/usa.png
  web/public/images/yeungjinLogo.svg
  web/public/images/yeungjinTitlePicture.jpg
  web/src/SideMenu.tsx
  web/src/app/(TitleLayout)/components/EditorCategoryLanguage.tsx
  web/src/app/(TitleLayout)/components/ManagementCookieCompo.tsx
  web/src/app/(TitleLayout)/components/Title.tsx
  web/src/app/(TitleLayout)/layout.tsx
  web/src/app/layout.tsx
  web/src/app/menu.tsx
Labels: 🎨 Html & Css, ⭐ Feature

#29 ✨ feat : BoardPage 수정
  web/src/app/(NoLayout)/login/page.tsx
  web/src/app/(TitleLayout)/components/BoardPageButton.tsx
  web/src/app/(TitleLayout)/components/BoardPageCompo.tsx
  web/src/app/(TitleLayout)/components/BoardPageContent.tsx
  web/src/app/(TitleLayout)/components/BoardPageSearch.tsx
  web/src/app/(TitleLayout)/components/HtmlDocs.tsx
Labels: 🛠️ Refactor

#32 🔨 CD : make deploy.yml
  .github/workflows/deploy.yml
  web/Dockerfile
Labels: 🚀 Deploy

#33 ✨ feat : admin페이지 전용 메뉴 제작
  web/src/app/(NoLayout)/layout.tsx
  web/src/app/(TitleLayout)/admin/components/AdminComponent.tsx
  web/src/app/(TitleLayout)/admin/components/CheckAdmin.tsx
  web/src/app/(TitleLayout)/admin/components/StaffComponent.tsx
  web/src/app/(TitleLayout)/admin/layout.tsx
Labels: 🎨 Html & Css

#40 🐛 fix : ESLint 수정, 파일 경로 수정
  web/src/app/(NoLayout)/components/AlertModal.tsx
  web/src/app/(NoLayout)/components/LoginForm.tsx
  web/src/app/(NoLayout)/components/RegisterCompo.tsx
  web/src/app/(NoTitleLayout)/home/components/EnrollmentInfo.tsx
  web/src/app/(NoTitleLayout)/home/components/HomeCompo.tsx
  web/src/app/(NoTitleLayout)/home/components/NewsCarousel.tsx
  web/src/app/(TitleLayout)/admin/components/AdminComponent.tsx
  web/src/app/(TitleLayout)/admin/components/ApplicationFormItem.tsx
  web/src/app/(TitleLayout)/admin/components/BannerPostModal.tsx
  web/src/app/(TitleLayout)/admin/components/CheckAdmin.tsx
  web/src/app/(TitleLayout)/admin/components/CounselingItem.tsx
  web/src/app/(TitleLayout)/admin/components/CounselingItemUpdateModal.tsx
  web/src/app/(TitleLayout)/admin/components/CourseModal.tsx
  web/src/app/(TitleLayout)/admin/components/DeleteModal.tsx
  web/src/app/(TitleLayout)/admin/components/StaffModal.tsx
  web/src/app/(TitleLayout)/components/BoardPageCompo.tsx
  web/src/app/(TitleLayout)/components/DashboardCompo.tsx
  web/src/app/(TitleLayout)/components/Editor.tsx
  web/src/app/(TitleLayout)/components/EditorTitle.tsx
  web/src/app/(TitleLayout)/components/HomePageCompo.tsx
  web/src/app/(TitleLayout)/components/HtmlDocs.tsx
  web/src/app/(TitleLayout)/components/HtmlDocsIdProps.tsx
  web/src/app/(TitleLayout)/components/MapCompo.tsx
  web/src/app/(TitleLayout)/components/NameChangeModal.tsx
  web/src/app/(TitleLayout)/components/Pagination.tsx
  web/src/app/(TitleLayout)/components/SelectPageCompo.tsx
  web/src/app/(TitleLayout)/components/StaffIntro.tsx
  web/src/app/common/formFile.ts
  web/src/app/hook/auth.ts
  web/src/app/hook/canEditOrDelete.ts
  web/src/app/hook/customFetch.ts
  web/src/app/hook/customFormFetch.ts
  web/src/app/lib/extractContent.ts
Labels: 🛠️ Refactor, 🐛 BugFix

#42 TitleLayaout폴더 수정, Hamburger메뉴 구현
  web/public/images/attachFile.png
  web/public/images/closeButton.png
  web/public/images/hamburgerMenu.png
  web/public/images/japan.png
  web/public/images/japan.svg
  web/public/images/korea.svg
  web/public/images/korean.png
  web/public/images/usa.png
  web/public/images/usa.svg
  web/public/images/xbutton.png
  web/src/SideMenu.tsx
  web/src/app/(NoTitleLayout)/layout.tsx
  web/src/app/(TitleLayout)/components/BoardPageButton.tsx
  web/src/app/(TitleLayout)/components/BoardPageCompo.tsx
  web/src/app/(TitleLayout)/components/BoardPageSearch.tsx
  web/src/app/(TitleLayout)/components/Editor.tsx
  web/src/app/(TitleLayout)/components/EditorButton.tsx
  web/src/app/(TitleLayout)/components/EditorTinyMCE.tsx
  web/src/app/(TitleLayout)/components/HamburgerMenuCompo.tsx
  web/src/app/(TitleLayout)/components/HtmlDocs.tsx
  web/src/app/(TitleLayout)/components/HtmlDocsHeaderProps.tsx
  web/src/app/(TitleLayout)/components/ManagementCookieCompo.tsx
  web/src/app/(TitleLayout)/layout.tsx
  web/src/app/hook/customFormFetch.ts
  web/src/app/layout.tsx
  web/src/app/menu.tsx
Labels: 🛠️ Refactor, 🎨 Html & Css

#44 ✨ feat : 로그인페이지, menu.tsx, layout.tsx, EnrollmentInfo.tsx, Editor.tsx 수정
  web/public/images/background.jpg
  web/src/app/(NoLayout)/components/LoginForm.tsx
  web/src/app/(NoLayout)/layout.tsx
  web/src/app/(NoTitleLayout)/home/components/EnrollmentInfo.tsx
  web/src/app/(NoTitleLayout)/layout.tsx
  web/src/app/(TitleLayout)/components/Editor.tsx
  web/src/app/(TitleLayout)/components/ManagementCookieCompo.tsx
  web/src/app/(TitleLayout)/layout.tsx
  web/src/app/layout.tsx
  web/src/app/menu.tsx
Labels: 🛠️ Refactor, 🎨 Html & Css, ⭐ Feature

#49 국제교류원 백엔드 api에 맞춰 코드 수정
  web/src/SideMenu.tsx
  web/src/app/(NoLayout)/components/LoginForm.tsx
  web/src/app/(TitleLayout)/admin/components/AdminComponent.tsx
  web/src/app/(TitleLayout)/admin/components/DeleteModal.tsx
  web/src/app/(TitleLayout)/admin/components/StaffComponent.tsx
  web/src/app/(TitleLayout)/admin/components/StaffModal.tsx
  web/src/app/(TitleLayout)/admin/layout.tsx
  web/src/app/(TitleLayout)/components/BoardPageCompo.tsx
  web/src/app/(TitleLayout)/components/BoardPageSearch.tsx
  web/src/app/(TitleLayout)/components/EditorButton.tsx
  web/src/app/(TitleLayout)/components/HtmlDocs.tsx
  web/src/app/(TitleLayout)/components/HtmlDocsDirection.tsx
  web/src/app/(TitleLayout)/components/MapCompo.tsx
  web/src/app/(TitleLayout)/components/StaffIntro.tsx
  web/src/app/(TitleLayout)/staff/components/StaffMapCompo.tsx
  web/src/app/common/types.tsx
  web/src/app/menu.tsx
Labels: 🛠️ Refactor, 🎨 Html & Css, ⭐ Feature
